apiVersion: v1
kind: Service
metadata:
  name: mj-gitops-app
spec:
  type: NodePort
  selector:
    app: mj-gitops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8008
      nodePort: 30080 # We will access the app on port 30080
